[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
cpmm = "5QWKxXbJjohpxLkEYk3G3yoirhRVVALZrBHzVThAnZyo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts"
deposit = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/deposit.test.ts"
